import { Varela_Round } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import Footer from "./_components/footer";

const varelaRound = Varela_Round({
  weight: '400',
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${varelaRound.className} bg-[url(/drone_frame.jpg)] min-h-screen bg-cover bg-center bg-no-repeat backdrop-blur-md`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
